spring:
  datasource:
    # H2 fallback (overridden by Testcontainers DataSource bean in tests)
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false

# Note: A Testcontainers PostgreSQL DataSource is provided in test scope to exercise
# jsonb columns and native SQL; Flyway remains disabled in tests via this profile.
