spring:
  datasource:
    # URL provided dynamically by EnhancedPostgresTestContainer
    # driver-class-name provided dynamically
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 5
      minimumIdle: 1
      maxLifetime: 60000    # >=30000ms to avoid Hikari warning; shorter for fast test recycle
      idleTimeout: 30000
      validationTimeout: 5000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

# Test profile uses singleton Postgres Testcontainer (EnhancedPostgresTestContainer).
# application-test.properties has been removed; all test config lives here.

smsarchive:
  import:
    inline: true      # process import synchronously in tests for deterministic progress
    batchSize: 500    # batch size for import persistence logic
